#!/bin/zsh

i=$1
while [ $i -gt 0 ]
do
    printf "\r%02d:%02d:%02d %s" $(($i/3600)) $(($i/60 % 60)) $(($i % 60)) $2
    sleep 1
    i=$(($i-1))
done
printf "\r%02d:%02d:%02d %s timer complete.\n\a" $(($1/3600)) $(($1/60 % 60)) $(($1 % 3600)) $2
printf "Press ^C to end ..."

while true
do 
    say -v "Ava" "$2 timer complete."
    sleep 10
done